name 'fokus-liferay'
version '0.0.1'
author 'Florian Thiemer'
license 'Apache License, Version 2.0'
source 'https://github.com/FLorian23/puppet-fokus-liferay.git'
summary 'Puppet module for liferay'
description 'This module installs liferay'
dependency 'example42/jboss', '>=2.0.1.0'
